/**************************************************************************************************************
 *
 * MODULE: DC motor
 *
 * FILE NAME: DC_motor.c
 *
 * Description: Source file for the DC motor driver
 *
 * Created on: October 9, 2022
 *
 * Author: Saeed Elsayed
 *
 **************************************************************************************************************/

#include "DC_motor.h"
#include "gpio.h"


uint8 duty_cycle;    // variable will carry the duty_cylcle wanted to be generated by the PWM

/*
 * Description:
 * function that initialize the DC motor
 */
void DcMotor_Init(){

	GPIO_setupPinDirection(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN1_ID, PIN_OUTPUT); // make the two pins (which are input
	GPIO_setupPinDirection(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN2_ID, PIN_OUTPUT); // for the DC motor) as output pins
	GPIO_setupPinDirection(DC_MOTOR_ENABLE_PORT_ID, DC_MOTOR_ENABLE_PIN_ID, PIN_OUTPUT); //make the enable pin as output pin
	GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN1_ID, LOGIC_LOW);  // first clear both of them
	GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN2_ID, LOGIC_LOW);  // to stop the DC motor

}

/*
 * Description:
 * function which determines the direction of rotation and speed of the DC motor
 */
void DcMotor_Rotate(DcMotor_State state,uint8 speed){
	if(state == STOP){              // if the state is off clear the two input pins of the motor
		                            // to prevent it from movement
		GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN1_ID, LOGIC_LOW);
		GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN2_ID, LOGIC_LOW);

	}
	else if(state == CLOCK_WISE){  // setting the first input pin of the motor and clearing the second will
		                           // make it rotate in the clock wise direction
		GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN2_ID, LOGIC_LOW);

	}
	else if(state == ANTI_CLOCK_WISE){  // clearing the first input pin of the motor and setting the second will
                                        // make it rotate in the anti clock wise direction

		GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN1_ID, LOGIC_LOW);
		GPIO_writePin(DC_MOTOR_PORT_ID, DC_MOTOR_INPUT_PIN2_ID, LOGIC_HIGH);

	}


// here the speed is ratio, and the maximum of the TNCT0 register is 255, so we will choose the duty
// cycle relevant to the TNCT0 maximum value to reach to the speed ratio wanted
	if(speed == 0){

		duty_cycle = 0;

	}

	else if(speed == 25){        //      speed is 25%

		duty_cycle = 64;         //      64/256 = 25%

		}
	else if(speed == 50){

		duty_cycle = 128;

		}
	else if(speed == 75){

		duty_cycle = 192;

		}
	else if(speed == 100){

		duty_cycle =255;

		}

}
